### ISSUE TITLE
Migrasi tidak bisa dijalankan

### ISSUE THREAD

**Issue by nmfzone** [laravolt/password#2]
### Versi

[v1.3.0](https://github.com/laravolt/password/releases/tag/1.3.0)

### _Link Reproduction_

Tidak ada.

### Langkah untuk _reproduce_

1. Install laravel
2. Ubah migrasi users menjadi `2019_06_10_000000_create_users_table.php`
3. Install Laravolt Password
4. Jalankan Migrasi

### Bagaimana seharusnya ?

Seharusnya migrasi sebuah package tidak boleh dependen dengan migrasi aplikasi. Dalam hal ini, migrasi `add_password_last_set_to_users` dependen dengan migrasi `create_users_table`. Sehingga, migrasi `create_users_table` perlu berada sebelum migrasi `add_password_last_set_to_users`.

Jika dependen seperti itu, maka perlu mekanisme untuk mem-publish migrasi sesuai tanggal `publish`.

### Apa yang terjadi ?

Karena tanggal migrasi `2015_09_30_000000_add_password_last_set_to_users.php` lebih awal dibanding migrasi `2019_06_10_000000_create_users_table.php`.

```
Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.users' doesn't exist (SQL: alter table `users` add `password_last_set` timestamp null after `password`)
```

### Saran / Komentar

Harusnya, migrasi `2015_09_30_000000_add_password_last_set_to_users.php` dapat dipublish & tanggal sesuai dengan tanggal publish, misalnya karena sekarang tanggal `13-06-2019`, maka ketika di publish migration menjadi `2019_06_13_000000_add_password_last_set_to_users.php`.

Mekanisme ini seperti yang ada pada package `Bouncer`. Berikut link nya..

https://github.com/JosephSilber/bouncer/blob/master/src/BouncerServiceProvider.php#L135

**Comment by uyab** [comment]
Ada kebutuhan apa ya sampai mengubah tanggal migrasi create_users_table ?

**Comment by nmfzone** [comment]
@uyab Kebutuhannya karena migrasi `create_users_table` dependen dengan table lain, yang terletak pada module lain.
Pada kasus ini `create_users_table` dependen dengan table `districts`, yang dimiliki oleh package `laravolt/indonesia`. Sehingga, perlu merename migrasi `create_user_table` agar berada setelah migrasi `laravolt/indonesia`.

Tapi, disamping itu, poin nya ini `Seharusnya migrasi sebuah package tidak boleh dependen dengan migrasi aplikasi.`.

**Comment by uyab** [comment]
`Seharusnya migrasi sebuah package tidak boleh dependen dengan migrasi aplikasi.` Apakah ini berarti mending bikin tabel terpisah daripada menambah kolom di existing tabel?

**Comment by uyab** [comment]
Ok, sementara nyontek https://github.com/spatie/laravel-permission/pull/962/files, berarti mau tidak mau harus publish migrations dulu

**Comment by nmfzone** [comment]
@uyab Bukan gitu..menambah kolom di exisiting table nggak masalah, yang jadi masalah `migrasi` nya jangan sampai dependen dgn migrasi lain. Dependen nggak masalah, asalkan migrasinya punya metode publish seperti yang ada di contoh di atas. Sehingga, tidak force user (pengguna package) untuk tetap mempunyai `create_users_table` sebelum tanggal yang dimiliki oleh package.

**Comment by nmfzone** [comment]
@uyab Yaps betul, jadi force nya cuman force user untuk publish migration. Dan, I think itu worth it..

**Comment by uyab** [comment]
Fixed in 1.4.0
